export enum JenisProdukID {
  GOA = 12,
  KUIS = 16,
  TOBK = 25,
  RUMUS = 46,
  VIDEO_EKSTRA = 57,
  TEORI = 59,
  VAK = 65,
  EMMA = 71,
  EMWA = 72,
  LATEKS = 76,
  PIN = 77,
  PASKOD = 78,
  PAMAT = 79,
  RACING = 80,
  SOREF = 82,
  VIDEO_SOAL = 87,
  VIDEO_TEORI = 88,
  SKMP = 99,
}

export enum JenisProdukNama {
  GOA = 'e-GOA',
  KUIS = 'e-Kuis',
  TOBK = 'e-TOBK',
  RUMUS = 'e-Rumus',
  VIDEO_EKSTRA = 'e-Video Ekstra',
  TEORI = 'e-Teori',
  VAK = 'e-VAK',
  EMMA = 'e-Empati Mandiri',
  EMWA = 'e-Empati Wajib',
  LATEKS = 'e-Latihan Ekstra',
  PIN = 'e-Paket Intensif',
  PASKOD = 'e-Paket Soal Koding',
  PAMAT = 'e-Pendalaman Materi',
  RACING = 'e-Racing',
  SOREF = 'e-SoRef',
  VIDEO_SOAL = 'e-Video Soal',
  VIDEO_TEORI = 'e-Video Teori',
  SKMP = 'e-SKMP',
}