export const PrismaErrorCodeMapper: Record<string, { message: string }> = {
    P2000: { message: "Input Data is too long" },
    P2001: { message: "Record does not exist" },
    P2002: { message: "Reference Data already exists" },
    P2003: { message: "Foreign key data in input does not exist" },
    P2004: { message: "A constraint failed on the database" },
    P2005: { message: "Invalid input field's type" },
    P2006: { message: "The provided value is not valid" },
    P2007: { message: "Data validation error" },
    P2011: { message: "Null constraint violation on the {constraint}" },
    P2012: { message: "Missing a required value at {path}" },
    P2013: { message: "Missing the required argument {argument_name} for field {field_name} on {object_name}." },
    P2014: { message: "The change you are trying to make would violate the required relation '{relation_name}' between the {model_a_name} and {model_b_name} models." },
    P2015: { message: "A related record could not be found. {details}" },
    P2016: { message: "Query interpretation error. {details}" },
    P2017: { message: "The records for relation {relation_name} between the {parent_name} and {child_name} models are not connected." },
    P2018: { message: "The required connected records were not found. {details}" },
    P2019: { message: "Input error. {details}" },
    P2020: { message: "Value out of range for the type. {details}" },
    P2021: { message: "The table {table} does not exist in the current database." },
    P2022: { message: "The column {column} does not exist in the current database." },
    P2023: { message: "Inconsistent column data: {message}" },
    P2024: { message: "Timed out fetching a new connection from the connection pool. (More info: http://pris.ly/d/connection-pool (Current connection pool timeout: {timeout} }, connection limit: {connection_limit})" },
    P2025: { message: "An operation failed because it depends on one or more records that were required but not found" },
    P2026: { message: "The current database provider doesn't support a feature that the query used: {feature}" },
    P2027: { message: "Multiple errors occurred on the database during query execution: {errors}" },
    P2028: { message: "Transaction API error: {error}" },
    P2030: { message: "Cannot find a fulltext index to use for the search }, try adding a @@fulltext([Fields...]) to your schema" },
    P2031: { message: "Prisma needs to perform transactions }, which requires your MongoDB server to be run as a replica set. See details: https://pris.ly/d/mongodb-replica-set" },
    P2033: { message: "A number used in the query does not fit into a 64 bit signed integer. Consider using BigInt as field type if you're trying to store large integers" },
    P2034: { message: "Transaction failed due to a write conflict or a deadlock. Please retry your transaction"}
}
  